name: GLaDOS-checkin

on:
  push:
  pull_request:
  fork:
  watch:
    types: [ started ]
  schedule:
    - cron: 0 */8 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
        
    - name: Checkin
      run: |
        python checkin.py 
      env: 
        SCKEY: ${{ secrets.SCKEY }}
        COOKIE: ${{ secrets.COOKIE }}