name: GLaDOS-checkin

on:
  push:
  pull_request:
  fork:
  watch:
    types: [ started ]
  schedule:
    - cron: 0 */12 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Checkin
      run: |
        python checkin.py 